version: '3'

services:
  master1:
    image: redis:7.0.4
    container_name: master1
    command: "redis-server /etc/redis.conf"
    volumes:
      - master1:/data
      - ./master.conf:/etc/redis.conf
    ports:
      - 10001:6379
  slave1:
    image: redis:7.0.4
    container_name: slave1
    command: "redis-server /etc/redis-config/redis.conf"
    ports:
      - 10002:6379
    volumes:
      - ./redis-config/slave.conf:/etc/redis-config/redis.conf
      - slave1:/data
    depends_on:
      - master1
  slave2:
    image: redis:7.0.4
    container_name: slave2
    command: "redis-server /etc/redis-config/redis.conf"
    ports:
      - 10003:6379
    volumes:
      - ./redis-config/slave.conf:/etc/redis-config/redis.conf
      - slave2:/data
    depends_on:
      - master1
  sentinel1:
    image: redis:7.0.4
    container_name: sentinel1
    command: "redis-server /etc/redis-config/sentinel.conf --sentinel"
    depends_on:
      - master1
      - slave1
      - slave2
    volumes:
      - ./redis-config/:/etc/redis-config/
  sentinel2:
    image: redis:7.0.4
    container_name: sentinel2
    command: "redis-server /etc/redis-config/sentinel.conf --sentinel"
    depends_on:
      - master1
      - slave1
      - slave2
    volumes:
      - ./redis-config/:/etc/redis-config/
  sentinel3:
    image: redis:7.0.4
    container_name: sentinel3
    command: "redis-server /etc/redis-config/sentinel.conf --sentinel"
    depends_on:
      - master1
      - slave1
      - slave2
    volumes:
      - ./redis-config/:/etc/redis-config/

volumes:
  master1:
  slave1:
  slave2:
  sentinel1:
  sentinel2:
  sentinel3: